### ISSUE TITLE
Communication issues between OpenUxAS and OpenAMASE using DAIDALUS_integration branch

### ISSUE THREAD

**Issue by VVCAS-Sean** [afrl-rq/OpenUxAS#16]
There is a known issue with the communication protocol between OpenUxAS and OpenAMASE when using the DAIDALUS_integration branch.  The current use of DAIDALUS requires an increased communication as each vehicle state update spawns a DAIDALUS evaluation and associated message.  This increase in communication can lead to messages being queued as OpenUxAS currently uses a single socket for sending and receiving.  The resolution of these queues can lead to delays from OpenAMASE. As a results the state information then provided by OpenAMASE can be called into question.  This phenomena has been observed in those examples that inherently have a higher communication burden due to camera pointing based on state updates during line searches (e.g. Examples 4, 11, and 12).

**Comment by pwilliams12** [comment]
The following pull request has a proposed solution to this problem, but currently CI process is failing and needs addressed first: Pull Request #48

**Comment by manthonyaiello** [comment]
Didn't notice that #48 was merged; closing this issue.
