### ISSUE TITLE
use Alire to install Ada tools

### ISSUE THREAD

**Issue by manthonyaiello** [afrl-rq/OpenUxAS#72]
GNAT Community Edition was retired after the 2020 release. The preferred way to install community versions of Ada tools is to use Alire: https://alire.ada.dev/. The infrastructure should be updated to use Alire.

**Comment by VVCAS-Sean** [comment]
Note: Errors occur when building on Ubuntu 20.04 due to switch to Alire for Ada tools.  Expected changes to Alire build process expected to fix error.
